### ISSUE TITLE
News banner error

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/sunstar-foundation#39]
This error is seen loading [home page](https://main--sunstar-foundation--hlxsites.hlx.page/)
```
lib-franklin.js:447 failed to load module for news-banner TypeError: Cannot read properties of undefined (reading 'newstext')
    at Module.decorate (news-banner.js:39:37)
    at async lib-franklin.js:443:15
```

**Comment by jindaliiita** [comment]
Added **helix-ja-search** sheet in **query-index**
